language: node_js # 声明环境为node
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules # 缓存node_modules文件夹

# S: Build Lifecycle
install:
  - npm install # 下载依赖

before_script:

script:
  - npm run build # 打包

after_script: # 推送到github的部分
  - cd ./build
  - git init
  - git config user.name "zengpeng123"
  - git config user.email "1042289178@qq.com"
  - git add .
  - git commit -m "release version"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH} # 通过之前存在Travis-CI里的token以及github仓库的地址推送到相应的分支
# E: Build LifeCycle

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master

env: # 环境变量
  global:
    # - GH_REF: github.com/zengpeng123/react-template.git # 我的仓库地址,我将其添加到了travis-ci的环境变量中

# 发布版本
deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  # file: react-template.zip
  skip_cleanup: true
  on:
    tags: true
